name: kyle-action

on:
  push:
    branches: [ kyle-cicd ]

jobs:
  deploy-api:
    environment: kyle-staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build project with Maven
        run: mvn package -Pkyle-staging
      - name: SCP bundle to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.KYLE_STAGING_HOST }}
          username: ${{ secrets.KYLE_STAGING_USERNAME }}
          key: ${{ secrets.KYLE_STAGING_KEY }}
          source: "./target"
          target: ${{ secrets.KYLE_PENGUIN_API_DEPLOY_DIRECTORY }}
